export const API_REQUEST_RUNNING = 'API_REQUEST_RUNNING';
export const API_REQUEST_ERROR = 'API_REQUEST_ERROR';

export const CREATE_PET_SUCCESS = 'CREATE_PET_SUCCESS';
export const REMOVE_PET_SUCCESS = 'REMOVE_PET_SUCCESS';
export const UPDATE_PET_SUCCESS = 'UPDATE_PET_SUCCESS';
export const CLEAR_PET_SUCCESS = 'CLEAR_PET_SUCCESS';
export const FETCH_PETS_SUCCESS = 'FETCH_PET_SUCCESS';
export const FETCH_PET_BY_ID_SUCCESS = 'FETCH_PET_BY_ID_SUCCESS';